// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoalA.Context;

#nullable disable

namespace SoalA.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220922222624_changeColumn2")]
    partial class changeColumn2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SoalA.Models.Barang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Jumlah_Barang")
                        .HasColumnType("int");

                    b.Property<string>("Kode_Barang")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nama_Barang")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MS_Barang");
                });
#pragma warning restore 612, 618
        }
    }
}
